name: Build Release APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Release APK
        run: flutter build apk --release

      - name: Upload APK to Temporary Server (transfer.sh)
        run: |
          # Yüklemeyi yap ve dönen linki değişkene kaydet
          DOWNLOAD_URL=$(curl -T build/app/outputs/flutter-apk/app-release.apk https://transfer.sh/app-release.apk)
          
          # GitHub Actions anasayfasına not olarak yazdır
          echo "### 🚀 APK Dosyanız Hazır!" >> $GITHUB_STEP_SUMMARY
          echo "Ziplenmemiş ham APK dosyasını aşağıdaki linkten indirebilirsiniz (14 gün geçerlidir):" >> $GITHUB_STEP_SUMMARY
          echo "[📥 app-release.apk İndir]($DOWNLOAD_URL)" >> $GITHUB_STEP_SUMMARY
